# Generated by Django 4.2.16 on 2024-11-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
